name: google_ads_helper
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/google_ads_helper

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  app_tracking_transparency: ^2.0.3
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.3.0
  package_info_plus: ^3.0.2
  satisfied_version: ^0.1.0+1
  shared_preferences: ^2.0.16
  universal_platform: ^1.0.0+1
  box_widgets:
    git: https://github.com/vursin/box_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
 
